# This is a basic workflow to help you get started with Actions

name: Check Proper Format

# Controls when the workflow will run
on: 
  pull_request:
    types: [opened, reopened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  format_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run lint
        run: npm run lint

      # Runs a set of commands using the runners shell
      - name: Run format-check
        run: npm run format-check
        
      - name: Run type-check
        run: npm run type-check
      
      - name: Run test
        run: npm run test
